/* ------------------------------------------------------------------
   Outbound URLs.

   Nothing published is re-hosted: a record carries a reference and the
   URL is built from it.  These four builders are the only place that
   knows the shape of an external address.
   ------------------------------------------------------------------ */

/* Behance serves project covers from an unsigned, stable CDN path, so a
   tile can show the real cover without a copy living in this repo. */
const BE_CDN = 'https://mir-s3-cdn-cf.behance.net/';

/* 'assets/...' is ours; anything else is a Behance CDN path */
export const coverUrl = (path) =>
  !path ? '' : (path.startsWith('assets/') ? path : BE_CDN + path);

/* { id, slug } -> behance.net/gallery/<id>/<slug> */
export const behanceUrl = (b) =>
  'https://www.behance.net/gallery/' + b.id + '/' + b.slug;

/* { code, kind } -> instagram.com/<kind>/<code>/   kind: 'p' | 'reel'
   Thumbnails *are* saved locally, in assets/covers/instagram/<code>.jpg,
   because Instagram's CDN URLs are signed and expire. */
export const igUrl = (p) =>
  'https://www.instagram.com/' + p.kind + '/' + p.code + '/';

/* Every clip in assets/web has a poster beside it in assets/posters,
   generated by tools/media.mjs.  A wall of tiles shows posters — about
   40 KB each — and fetches no video at all until something is hovered,
   which is the difference between a mosaic costing half a megabyte and
   costing fifty. */
export const posterUrl = (clip) =>
  !clip || !clip.startsWith('assets/web/') ? ''
    : clip.replace(/^assets\/web\//, 'assets/posters/').replace(/\.(webm|mp4|mov)$/i, '.jpg');

/* a case study owns a page; an archive entry does not */
export const projectUrl = (p) => 'project.html?p=' + p.slug;

export const sectorUrl = (s) => (typeof s === 'string' ? s : s.id) + '.html';
