/* ------------------------------------------------------------------
   What is on each page, and in what order.

   GENERATED by tools/allocate.mjs from content/allocation_new.csv.
   Edit the spreadsheet and re-run it rather than editing this file —
   the order here is a running order somebody chose, not something to
   be tidied alphabetically.

   Each page is ONE flat list. There is no archive section and no
   Instagram strip: an entry is an entry, and what it happens to be
   only decides where clicking it goes —

     'muse-watch'        a project with a page here
     'aloka'             a published gallery, opens on Behance
     'ig:Cy75XuoSpS8'    an Instagram post, opens there

   A record that appears in no list simply is not shown anywhere. It is
   not deleted: projects.js still has it, so an old link to it still
   resolves and it can be put back by adding one line to the sheet.
   ------------------------------------------------------------------ */

export const PAGES = {
  /* Industrial Design — 18 entries */
  'industrial-design': [
    'muse-watch',
    'john-jacobs-masaba',
    'aloka-2',
    'cosmo-footwear',
    'bbc-league-trophy',
    'toruk-custom-bike',
    'ig:Cy75XuoSpS8',
    'worldskills-regionals',
    'e-waste-system-design',
    'jeev-pendant-light',
    'dabur-vatika-bottle',
    'ig:DEm5d3BtpuF',
    'aloka',
    'dfo-headphones',
    'monsoon-fiesta-trophy',
    'form-studies',
    'red-raven-toy',
    'mobius-ring'
  ],

  /* Technical Art — 9 entries */
  'technical-art': [
    'strandbeest',
    'ig:DBblehryOvP',
    'ig:C5qKbaqoS81',
    'ig:DZhUGT6zLUH',
    'ig:C3xN8HcSitr',
    'product-teardown',
    'ig:DY5Se7pTini',
    'ig:C_fxgvZo0Jm',
    'ig:C30IwA0S86z'
  ],

  /* Visualization — 26 entries */
  'visualization': [
    'mushroom-fiend',
    'ig:C5S8PcUyYaS',
    'product-visualisation',
    'ig:C4zkP75yvL3',
    'ig:DY1ZLdrzDMn',
    'ig:DGdAAn0oQAJ',
    'ig:DYob7EGT4Rb',
    'installation',
    'ig:C6eGhKYIsUI',
    'ig:CxA3q1JS0za',
    'old-works',
    'nid-foundation',
    'ig:DCzA-Kmozdd',
    'ig:CxrwSzcyniD',
    'ig:CPIeojBp4YM',
    'digital-illustration',
    'photography',
    'ig:DEhw2rOKdE8',
    'ig:C7ONyGwI_ay',
    'ig:DBi2HkxIX1H',
    'ig:DCoVgrcIE9J',
    'ig:DYoJ6mfTi0C',
    'ig:C93AJFvIDgv',
    'dreamhome',
    'ig:CFghnTnJad_',
    'ig:DV8nZzIkxXn'
  ]
};

export const pageRefs = (sectorId) => PAGES[sectorId] || [];
