// GENERATED by tools/build_catalog.mjs from "Fitmint - Male.csv" - do not edit by hand.
export const catalog = {
  "avatar": {
    "model": "assets/opt/Male.glb?v=1789107982156"
  },
  "categories": {
    "skin": {
      "label": "Skin",
      "icon": "skin",
      "kind": "texture",
      "target": "body",
      "items": [
        {
          "id": "maleTexture_1",
          "label": "Tone 01",
          "texture": "assets/tex/skin/maleTexture_1.webp?v=1789108002441",
          "thumb": "assets/tex/skin/maleTexture_1.thumb.webp?v=1789108002466"
        },
        {
          "id": "maleTexture_2",
          "label": "Tone 02",
          "texture": "assets/tex/skin/maleTexture_2.webp?v=1789108002520",
          "thumb": "assets/tex/skin/maleTexture_2.thumb.webp?v=1789108002543"
        },
        {
          "id": "maleTexture_3",
          "label": "Tone 03",
          "texture": "assets/tex/skin/maleTexture_3.webp?v=1789108002597",
          "thumb": "assets/tex/skin/maleTexture_3.thumb.webp?v=1789108002619"
        },
        {
          "id": "maleTexture_4",
          "label": "Tone 04",
          "texture": "assets/tex/skin/maleTexture_4.webp?v=1789108002673",
          "thumb": "assets/tex/skin/maleTexture_4.thumb.webp?v=1789108002696"
        },
        {
          "id": "maleTexture_5",
          "label": "Tone 05",
          "texture": "assets/tex/skin/maleTexture_5.webp?v=1789108002748",
          "thumb": "assets/tex/skin/maleTexture_5.thumb.webp?v=1789108002771"
        },
        {
          "id": "maleTexture_6",
          "label": "Tone 06",
          "texture": "assets/tex/skin/maleTexture_6.webp?v=1789108002823",
          "thumb": "assets/tex/skin/maleTexture_6.thumb.webp?v=1789108002844"
        }
      ]
    },
    "eye": {
      "label": "Eyes",
      "icon": "eye",
      "kind": "texture",
      "target": "Eye",
      "items": [
        {
          "id": "eye_1",
          "label": "Iris 01",
          "texture": "assets/tex/eye/eye_1.webp?v=1789108002458",
          "thumb": "assets/tex/eye/eye_1.thumb.webp?v=1789108002470"
        },
        {
          "id": "eye_2",
          "label": "Iris 02",
          "texture": "assets/tex/eye/eye_2.webp?v=1789108002538",
          "thumb": "assets/tex/eye/eye_2.thumb.webp?v=1789108002548"
        },
        {
          "id": "eye_3",
          "label": "Iris 03",
          "texture": "assets/tex/eye/eye_3.webp?v=1789108002614",
          "thumb": "assets/tex/eye/eye_3.thumb.webp?v=1789108002624"
        },
        {
          "id": "eye_4",
          "label": "Iris 04",
          "texture": "assets/tex/eye/eye_4.webp?v=1789108002692",
          "thumb": "assets/tex/eye/eye_4.thumb.webp?v=1789108002701"
        },
        {
          "id": "eye_5",
          "label": "Iris 05",
          "texture": "assets/tex/eye/eye_5.webp?v=1789108002766",
          "thumb": "assets/tex/eye/eye_5.thumb.webp?v=1789108002775"
        },
        {
          "id": "eye_6",
          "label": "Iris 06",
          "texture": "assets/tex/eye/eye_6.webp?v=1789108002839",
          "thumb": "assets/tex/eye/eye_6.thumb.webp?v=1789108002848"
        }
      ]
    },
    "hair": {
      "label": "Hair",
      "icon": "hair",
      "kind": "mesh",
      "slot": "hair",
      "optional": true,
      "recolor": true,
      "items": [
        {
          "id": "hair02",
          "label": "Hair 02",
          "model": "assets/opt/hair/hair02.glb?v=1789107991599",
          "thumb": "assets/thumbs/hair/hair02.webp?v=1789106829695"
        },
        {
          "id": "hair03",
          "label": "Hair 03",
          "model": "assets/opt/hair/hair03.glb?v=1789107992035",
          "thumb": "assets/thumbs/hair/hair03.webp?v=1789106829708"
        },
        {
          "id": "hair04",
          "label": "Hair 04",
          "model": "assets/opt/hair/hair04.glb?v=1789107992491",
          "thumb": "assets/thumbs/hair/hair04.webp?v=1789106829722"
        },
        {
          "id": "hair05",
          "label": "Hair 05",
          "model": "assets/opt/hair/hair05.glb?v=1789107992920",
          "thumb": "assets/thumbs/hair/hair05.webp?v=1789106829736"
        },
        {
          "id": "hair06",
          "label": "Hair 06",
          "model": "assets/opt/hair/hair06.glb?v=1789107993369",
          "thumb": "assets/thumbs/hair/hair06.webp?v=1789106829749"
        },
        {
          "id": "hair07",
          "label": "Hair 07",
          "model": "assets/opt/hair/hair07.glb?v=1789107993817",
          "thumb": "assets/thumbs/hair/hair07.webp?v=1789106829763"
        },
        {
          "id": "hair08",
          "label": "Hair 08",
          "model": "assets/opt/hair/hair08.glb?v=1789107994251",
          "thumb": "assets/thumbs/hair/hair08.webp?v=1789106829780"
        },
        {
          "id": "hair09",
          "label": "Hair 09",
          "model": "assets/opt/hair/hair09.glb?v=1789107994703",
          "thumb": "assets/thumbs/hair/hair09.webp?v=1789106829795"
        }
      ]
    },
    "facialHair": {
      "label": "Facial Hair",
      "icon": "beard",
      "kind": "mesh",
      "slot": "facialHair",
      "optional": true,
      "recolor": true,
      "items": [
        {
          "id": "Beard01",
          "label": "Beard 01",
          "model": "assets/opt/facialHair/Beard01.glb?v=1789107986317",
          "thumb": "assets/thumbs/facialHair/Beard01.webp?v=1789106829561"
        },
        {
          "id": "Beard02",
          "label": "Beard 02",
          "model": "assets/opt/facialHair/Beard02.glb?v=1789107986807",
          "thumb": "assets/thumbs/facialHair/Beard02.webp?v=1789106829574"
        },
        {
          "id": "Beard03",
          "label": "Beard 03",
          "model": "assets/opt/facialHair/Beard03.glb?v=1789107987306",
          "thumb": "assets/thumbs/facialHair/Beard03.webp?v=1789106829587"
        },
        {
          "id": "Beard04",
          "label": "Beard 04",
          "model": "assets/opt/facialHair/Beard04.glb?v=1789107987780",
          "thumb": "assets/thumbs/facialHair/Beard04.webp?v=1789106829599"
        },
        {
          "id": "Beard05",
          "label": "Beard 05",
          "model": "assets/opt/facialHair/Beard05.glb?v=1789107988269",
          "thumb": "assets/thumbs/facialHair/Beard05.webp?v=1789106829611"
        },
        {
          "id": "Beard06",
          "label": "Beard 06",
          "model": "assets/opt/facialHair/Beard06.glb?v=1789107988781",
          "thumb": "assets/thumbs/facialHair/Beard06.webp?v=1789106829625"
        }
      ]
    },
    "eyebrow": {
      "label": "Brows",
      "icon": "brow",
      "kind": "morphPreset",
      "target": "Eyebrow",
      "optional": true,
      "items": [
        {
          "id": "Eyebrow 1",
          "label": "Brow 01"
        },
        {
          "id": "Eyebrow 2",
          "label": "Brow 02"
        },
        {
          "id": "Eyebrow 3",
          "label": "Brow 03"
        },
        {
          "id": "Eyebrow 4",
          "label": "Brow 04"
        }
      ]
    },
    "headgear": {
      "label": "Headgear",
      "icon": "headgear",
      "kind": "mesh",
      "slot": "headgear",
      "optional": true,
      "items": [
        {
          "id": "sportsGlasses",
          "label": "Sports Glasses",
          "model": "assets/opt/headgear/sportsGlasses.glb?v=1789107997489",
          "thumb": "assets/thumbs/headgear/sportsGlasses.webp?v=1789106829873"
        },
        {
          "id": "nounGlasses",
          "label": "Noun Glasses",
          "model": "assets/opt/headgear/nounGlasses.glb?v=1789107996434",
          "thumb": "assets/thumbs/headgear/nounGlasses.webp?v=1789106829841"
        },
        {
          "id": "olympianGlasses",
          "label": "Olympian Glasses",
          "model": "assets/opt/headgear/olympianGlasses.glb?v=1789107996840",
          "thumb": "assets/thumbs/headgear/olympianGlasses.webp?v=1789106829858"
        },
        {
          "id": "balaclava",
          "label": "Balaclava",
          "model": "assets/opt/headgear/balaclava.glb?v=1789107995409",
          "thumb": "assets/thumbs/headgear/balaclava.webp?v=1789106829811"
        },
        {
          "id": "helmet",
          "label": "Helmet",
          "model": "assets/opt/headgear/helmet.glb?v=1789107996016",
          "thumb": "assets/thumbs/headgear/helmet.webp?v=1789106829825"
        }
      ]
    },
    "top": {
      "label": "Top",
      "icon": "top",
      "kind": "mesh",
      "slot": "top",
      "optional": true,
      "recolor": true,
      "items": [
        {
          "id": "vest",
          "label": "Tank Vest",
          "model": "assets/opt/top/vest.glb?v=1789108002368",
          "thumb": "assets/thumbs/top/vest.webp?v=1789106829981"
        },
        {
          "id": "tshirt",
          "label": "T-Shirt",
          "model": "assets/opt/top/tshirt.glb?v=1789108001050",
          "thumb": "assets/thumbs/top/tshirt.webp?v=1789106829950"
        },
        {
          "id": "tshirt_sleeve",
          "label": "Tee + Tattoo Sleeve",
          "model": "assets/opt/top/tshirt_sleeve.glb?v=1789109693785",
          "thumb": "assets/thumbs/top/tshirt_sleeve.webp?v=1789109698700"
        },
        {
          "id": "hoodie",
          "label": "Hoodie",
          "model": "assets/opt/top/hoodie.glb?v=1789107999485",
          "thumb": "assets/thumbs/top/hoodie.webp?v=1789106829918"
        },
        {
          "id": "militaryVest",
          "label": "Military Vest",
          "model": "assets/opt/top/militaryVest.glb?v=1789108000414",
          "thumb": "assets/thumbs/top/militaryVest.webp?v=1789106829934"
        }
      ]
    },
    "bottom": {
      "label": "Bottom",
      "icon": "bottom",
      "kind": "mesh",
      "slot": "bottom",
      "optional": true,
      "recolor": true,
      "items": [
        {
          "id": "shorts",
          "label": "Shorts",
          "model": "assets/opt/bottom/shorts.glb?v=1789107985811",
          "thumb": "assets/thumbs/bottom/shorts.webp?v=1789106829533"
        },
        {
          "id": "jogger",
          "label": "Joggers",
          "model": "assets/opt/bottom/jogger.glb?v=1789107984187",
          "thumb": "assets/thumbs/bottom/jogger.webp?v=1789106829516"
        },
        {
          "id": "short_leggin",
          "label": "Shorts + Leggings",
          "model": "assets/opt/bottom/short_leggin.glb?v=1789107985063",
          "thumb": "assets/thumbs/bottom/short_leggin.webp?v=1789106829548"
        },
        {
          "id": "cargo",
          "label": "Cargo Pants",
          "model": "assets/opt/bottom/cargo.glb?v=1789107982810",
          "thumb": "assets/thumbs/bottom/cargo.webp?v=1789106829483"
        },
        {
          "id": "cargoShorts",
          "label": "Cargo Shorts",
          "model": "assets/opt/bottom/cargoShorts.glb?v=1789107983555",
          "thumb": "assets/thumbs/bottom/cargoShorts.webp?v=1789106829501"
        }
      ]
    },
    "footwear": {
      "label": "Footwear",
      "icon": "footwear",
      "kind": "mesh",
      "slot": "footwear",
      "optional": true,
      "items": [
        {
          "id": "sneaker1",
          "label": "Runner 01",
          "model": "assets/opt/footwear/sneaker1.glb?v=1789107989393",
          "thumb": "assets/thumbs/footwear/sneaker1.webp?v=1789106829640"
        },
        {
          "id": "sneaker2",
          "label": "Runner 02",
          "model": "assets/opt/footwear/sneaker2.glb?v=1789107990051",
          "thumb": "assets/thumbs/footwear/sneaker2.webp?v=1789106829653"
        },
        {
          "id": "sneaker3",
          "label": "Champion Boot",
          "model": "assets/opt/footwear/sneaker3.glb?v=1789107990689",
          "thumb": "assets/thumbs/footwear/sneaker3.webp?v=1789106829667"
        },
        {
          "id": "sneaker4",
          "label": "Alien Sneaker",
          "model": "assets/opt/footwear/sneaker4.glb?v=1789107991164",
          "thumb": "assets/thumbs/footwear/sneaker4.webp?v=1789106829681"
        }
      ]
    },
    "overalls": {
      "label": "Overalls",
      "icon": "overalls",
      "kind": "mesh",
      "slot": "overalls",
      "optional": true,
      "recolor": true,
      "items": [
        {
          "id": "GOAT",
          "label": "G.O.A.T.",
          "model": "assets/opt/overalls/GOAT.glb?v=1789116292921",
          "thumb": "assets/thumbs/overalls/GOAT.webp?v=1789116313617"
        },
        {
          "id": "ALIEN",
          "label": "Alien",
          "model": "assets/opt/overalls/ALIEN.glb?v=1789113124559",
          "thumb": "assets/thumbs/overalls/ALIEN.webp?v=1789111019191"
        }
      ]
    },
    "faceDetail": {
      "label": "Face Detail",
      "icon": "face",
      "kind": "morphSliders",
      "target": "body",
      "excluded": [
        "facewidth"
      ],
      "groups": [
        {
          "name": "Face",
          "sliders": [
            {
              "id": "faceshape01",
              "label": "Faceshape 01"
            },
            {
              "id": "faceshape02",
              "label": "Faceshape 02"
            }
          ]
        },
        {
          "name": "Nose",
          "sliders": [
            {
              "id": "nosewidth",
              "label": "Nosewidth"
            },
            {
              "id": "nosenarrow",
              "label": "Nosenarrow"
            },
            {
              "id": "noseshape01",
              "label": "Noseshape 01"
            },
            {
              "id": "noseshape02",
              "label": "Noseshape 02"
            },
            {
              "id": "noseshape03",
              "label": "Noseshape 03"
            },
            {
              "id": "noseshape04",
              "label": "Noseshape 04"
            },
            {
              "id": "noseshape05",
              "label": "Noseshape 05"
            },
            {
              "id": "noseshape06",
              "label": "Noseshape 06"
            }
          ]
        },
        {
          "name": "Eyes",
          "sliders": [
            {
              "id": "eyeshape01",
              "label": "Eyeshape 01"
            },
            {
              "id": "eyeshape02",
              "label": "Eyeshape 02"
            },
            {
              "id": "eyeshape03",
              "label": "Eyeshape 03"
            },
            {
              "id": "eyeshape04",
              "label": "Eyeshape 04"
            },
            {
              "id": "eyeshape05",
              "label": "Eyeshape 05"
            },
            {
              "id": "eyeshape06",
              "label": "Eyeshape 06"
            },
            {
              "id": "eyeshape07",
              "label": "Eyeshape 07"
            },
            {
              "id": "eyeshape08",
              "label": "Eyeshape 08"
            },
            {
              "id": "eyeshape09",
              "label": "Eyeshape 09"
            }
          ]
        },
        {
          "name": "Mouth",
          "sliders": [
            {
              "id": "lipwidth",
              "label": "Lipwidth"
            },
            {
              "id": "lipshape01",
              "label": "Lipshape 01"
            },
            {
              "id": "lipshape02",
              "label": "Lipshape 02"
            }
          ]
        },
        {
          "name": "Build",
          "sliders": [
            {
              "id": "abs",
              "label": "Abs"
            }
          ]
        }
      ]
    },
    "animation": {
      "label": "Animation",
      "icon": "animation",
      "kind": "animation",
      "items": [
        {
          "id": "stretch",
          "label": "Stretch"
        },
        {
          "id": "Running_M",
          "label": "Running M"
        },
        {
          "id": "Walking_M",
          "label": "Walking M"
        },
        {
          "id": "hands on hip",
          "label": "Hands On Hip"
        },
        {
          "id": "folded hands",
          "label": "Folded Hands"
        },
        {
          "id": "idle",
          "label": "Idle"
        },
        {
          "id": "Active Idle",
          "label": "Active Idle"
        }
      ]
    }
  },
  "rules": {
    "overalls": {
      "clears": [
        "top",
        "bottom",
        "footwear"
      ],
      "restoreOnRemove": true
    },
    "top": {
      "clears": [
        "overalls"
      ]
    },
    "bottom": {
      "clears": [
        "overalls"
      ]
    },
    "footwear": {
      "clears": [
        "overalls"
      ]
    }
  },
  "recolorLimit": {
    "cargo": 1
  },
  "recolorGroups": {
    "GOAT": [
      {
        "id": "suit",
        "label": "Suit",
        "materials": [
          "G.bodysuit.1",
          "G.bodysuit.3",
          "G.bag.4",
          "G.shoe.1"
        ]
      },
      {
        "id": "trim",
        "label": "Pockets & trim",
        "materials": [
          "G.bodysuit.2",
          "G.bag.2",
          "G.bag.3",
          "G.glove.3",
          "G.shoe.4",
          "G.shoe.6"
        ]
      }
    ],
    "ALIEN": [
      {
        "id": "suit",
        "label": "Suit",
        "materials": [
          "A_shortsColor1",
          "A_vestColor1"
        ]
      },
      {
        "id": "accent",
        "label": "Accent",
        "materials": [
          "A_maskColor2",
          "A_shortsColor2",
          "A_vestColor3",
          "A_Sneaker1C2"
        ]
      }
    ]
  },
  "hides": {
    "helmet": [
      "hair",
      "facialHair"
    ],
    "balaclava": [
      "hair",
      "facialHair"
    ],
    "ALIEN": [
      "hair",
      "facialHair",
      "headgear"
    ]
  },
  "defaults": {
    "skin": "maleTexture_3",
    "eye": "eye_1",
    "hair": "hair04",
    "eyebrow": "Eyebrow 1",
    "top": "tshirt",
    "bottom": "jogger",
    "footwear": "sneaker1",
    "animation": "idle"
  },
  "missing": [
    "FaceDetail \"facewidth\" withheld - widens the head past the hair and headgear, which then clip",
    "Facial Hair \"Beard07\" listed in CSV but no source mesh on disk - skipped",
    "Facial Hair \"Beard08\" listed in CSV but no source mesh on disk - skipped"
  ]
};
