// GENERATED by tools/build_env.mjs from the source HDRIs - do not edit by hand.
//
// Measured from the HDRI: the key light sits where the dominant light in that
// image actually is, so its cast shadow agrees with it, and exposure is
// normalised so any environment lights the avatar to the same level. Fill and
// rim are not here - the character carries its own point-light rig for those.
// The HDRI itself is never shown; the stage is a plain white-to-grey gradient.
export const ENVIRONMENTS = [
  {
    "id": "TCom_ColorfulAlley_colorful_alley_1K_hdri_sphere",
    "label": "Alley",
    "hdr": "assets/env/TCom_ColorfulAlley_colorful_alley_1K_hdri_sphere.hdr?v=1789117200926",
    "envIntensity": 0.542,
    "exposure": 1,
    "key": {
      "color": 16776957,
      "intensity": 2.19,
      "position": [
        0.46,
        3.618,
        1.642
      ]
    },
    "shadow": 0.22
  }
];

export const DEFAULT_ENVIRONMENT = "TCom_ColorfulAlley_colorful_alley_1K_hdri_sphere";
