/* ------------------------------------------------------------------
   Turn the allocation spreadsheet into js/pages.js.

     node tools/allocate.mjs [content/allocation_new.csv]

   The CSV has one column per page — ID, VIZ, TD — and one entry per
   cell, top to bottom in the order it should appear.  A cell is either
   a project title or an Instagram entry written as "IG · <title>",
   optionally followed by "(in <parent project>)", which is only there
   to make the sheet readable and is ignored here.

   Everything on a page is one flat list.  There is no separate archive
   block and no Instagram strip: a page is the sequence its column
   says it is, and what a given entry happens to be only decides where
   clicking it goes.

   Run it whenever the sheet changes, then `node tools/sitemap.mjs`.
   ------------------------------------------------------------------ */

import { readFileSync, writeFileSync } from 'node:fs';
import { PROJECTS, ARCHIVE, POSTS } from '../js/projects.js';
import { SECTIONS } from '../js/sectors.js';

const SRC = process.argv[2] || new URL('../content/allocation_new.csv', import.meta.url).pathname.replace(/^\//, '');
const COLUMNS = { ID: 'industrial-design', VIZ: 'visualization', TD: 'technical-art' };

/* --- read the sheet ------------------------------------------------ */

function parseCsv(text) {
  const rows = [];
  let row = [], cell = '', quoted = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (quoted) {
      if (ch === '"' && text[i + 1] === '"') { cell += '"'; i++; }
      else if (ch === '"') quoted = false;
      else cell += ch;
    } else if (ch === '"') quoted = true;
    else if (ch === ',') { row.push(cell); cell = ''; }
    else if (ch === '\n') { row.push(cell); rows.push(row); row = []; cell = ''; }
    else if (ch !== '\r') cell += ch;
  }
  row.push(cell);
  if (row.some(c => c.trim())) rows.push(row);
  return rows;
}

/* --- index everything the sheet can name --------------------------- */

const byTitle = new Map();
for (const p of PROJECTS) byTitle.set(p.title, { ref: p.slug, kind: 'project' });
for (const p of ARCHIVE) byTitle.set(p.title, { ref: p.slug, kind: 'archive' });

const igByTitle = new Map();
for (const p of PROJECTS) for (const x of p.posts || []) igByTitle.set(x.title, x.code);
for (const list of Object.values(POSTS)) for (const x of list) igByTitle.set(x.title, x.code);

/* --- resolve each cell --------------------------------------------- */

const text = readFileSync(SRC, 'utf8').replace(/^﻿/, '');
const rows = parseCsv(text);
const header = rows[0].map(h => h.trim());
const pages = {};
const unknown = [];

for (const [col, sector] of Object.entries(COLUMNS)) {
  const i = header.indexOf(col);
  if (i === -1) { console.warn(`column ${col} not in the sheet — skipping`); continue; }
  const list = [];
  for (const row of rows.slice(1)) {
    const cell = (row[i] || '').trim();
    if (!cell) continue;
    if (cell.startsWith('IG · ')) {
      const title = cell.slice(5).replace(/\s*\(in .*\)$/, '').trim();
      const code = igByTitle.get(title);
      if (!code) { unknown.push(`${col}: ${cell}`); continue; }
      list.push('ig:' + code);
    } else {
      const hit = byTitle.get(cell);
      if (!hit) { unknown.push(`${col}: ${cell}`); continue; }
      list.push(hit.ref);
    }
  }
  pages[sector] = list;
}

if (unknown.length) {
  console.error('\nThese cells did not match anything in projects.js:\n  ' + unknown.join('\n  '));
  console.error('\nNothing written. Fix the sheet (or add the record) and run again.\n');
  process.exit(1);
}

/* --- write js/pages.js --------------------------------------------- */

const body = SECTIONS.map(s => {
  const list = pages[s.id] || [];
  const lines = list.map(r => `    '${r}'`).join(',\n');
  return `  /* ${s.title} — ${list.length} entries */\n  '${s.id}': [\n${lines}\n  ]`;
}).join(',\n\n');

const out = `/* ------------------------------------------------------------------
   What is on each page, and in what order.

   GENERATED by tools/allocate.mjs from content/allocation_new.csv.
   Edit the spreadsheet and re-run it rather than editing this file —
   the order here is a running order somebody chose, not something to
   be tidied alphabetically.

   Each page is ONE flat list. There is no archive section and no
   Instagram strip: an entry is an entry, and what it happens to be
   only decides where clicking it goes —

     'muse-watch'        a project with a page here
     'aloka'             a published gallery, opens on Behance
     'ig:Cy75XuoSpS8'    an Instagram post, opens there

   A record that appears in no list simply is not shown anywhere. It is
   not deleted: projects.js still has it, so an old link to it still
   resolves and it can be put back by adding one line to the sheet.
   ------------------------------------------------------------------ */

export const PAGES = {
${body}
};

export const pageRefs = (sectorId) => PAGES[sectorId] || [];
`;

writeFileSync(new URL('../js/pages.js', import.meta.url), out);

console.log('js/pages.js written from ' + SRC.split(/[\\/]/).pop());
for (const s of SECTIONS) {
  const list = pages[s.id] || [];
  const ig = list.filter(r => r.startsWith('ig:')).length;
  console.log(`  ${s.title.padEnd(20)} ${String(list.length).padStart(2)} entries  (${list.length - ig} projects, ${ig} Instagram)`);
}
