/* ------------------------------------------------------------------
   Pull the three faces into the repo, so the site has no third origin.

   Google Fonts costs two origins, not one: the stylesheet comes from
   fonts.googleapis.com and the files it names come from
   fonts.gstatic.com, which the browser cannot even begin to resolve
   until the first one has answered.  Two DNS lookups, two TLS
   handshakes and two round trips, in series, before a single glyph —
   and the whole chain sits in front of first paint because a
   stylesheet is render-blocking.

   So: ask Google for the CSS once, here, with a Chrome user agent so it
   answers in woff2; save the files it points at; and write a local
   stylesheet with the same @font-face rules and the same unicode-range
   splits, pointing at our copies.  Keeping the ranges matters — they
   are why a page that never shows a latin-ext character never
   downloads the latin-ext file.

       node tools/fonts.mjs            # fetch and write css/fonts.css
       node tools/fonts.mjs --check    # verify, write nothing, exit 1 on drift

   Licence: all three are SIL Open Font License 1.1, which is why this
   is allowed to be a copy rather than a link.  Re-run after changing a
   weight or adding a face; do not hand-edit css/fonts.css or anything
   under assets/fonts/.
   ------------------------------------------------------------------ */

import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { existsSync, statSync } from 'node:fs';

/* Exactly what the shells asked Google for, in the same order. */
const QUERY = [
  'family=Space+Grotesk:wght@400;600;700',
  'family=Stack+Sans+Notch:wght@400..700',
  'family=JetBrains+Mono:wght@400',
  'display=swap',
].join('&');

/* Google serves ttf to a UA it does not recognise and woff2 to a modern
   one.  woff2 is roughly 30% of the ttf, so the UA is load-bearing. */
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
           '(KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36';

const DIR = 'assets/fonts/';
const CSS = 'css/fonts.css';
const check = process.argv.includes('--check');

const res = await fetch(`https://fonts.googleapis.com/css2?${QUERY}`, { headers: { 'User-Agent': UA } });
if (!res.ok) throw new Error(`${res.status} ${res.statusText} from Google Fonts`);
let css = await res.text();

/* One file per (family, weight, subset).  The name is derived from the
   @font-face block it sits in rather than from the opaque gstatic path,
   so `ls assets/fonts/` reads as a list of faces instead of hashes. */
const blocks = [...css.matchAll(/@font-face\s*\{[^}]*\}/g)].map(m => m[0]);
const files = new Map();

for (const block of blocks) {
  const family = /font-family:\s*'([^']+)'/.exec(block)?.[1];
  const weight = /font-weight:\s*([^;]+)/.exec(block)?.[1].trim().replace(/\s+/g, '-');
  const url    = /url\((https:\/\/fonts\.gstatic\.com[^)]+)\)/.exec(block)?.[1];
  if (!family || !url) continue;

  const slug = family.toLowerCase().replace(/\s+/g, '-');
  /* the comment immediately above each block names its subset */
  const before = css.slice(0, css.indexOf(block));
  const label = [...before.matchAll(/\/\*\s*([\w-]+)\s*\*\//g)].pop()?.[1] ?? 'latin';
  const name = `${slug}-${weight}-${label}.woff2`;

  files.set(name, url);
  css = css.replace(url, `../${DIR}${name}`);
}

let drift = 0;
await mkdir(DIR, { recursive: true });

for (const [name, url] of files) {
  const dest = DIR + name;
  const bin = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  const current = existsSync(dest) ? await readFile(dest) : null;
  if (current && current.equals(bin)) continue;
  drift++;
  if (check) { console.log('DRIFT', dest); continue; }
  await writeFile(dest, bin);
}

const header = `/* Generated by tools/fonts.mjs — do not edit.\n` +
               `   Three faces, self-hosted, same unicode-range splits Google serves.\n` +
               `   SIL Open Font License 1.1. Re-run the tool to change a weight. */\n\n`;
const current = existsSync(CSS) ? await readFile(CSS, 'utf8') : null;
if (current !== header + css) {
  drift++;
  if (!check) await writeFile(CSS, header + css);
  else console.log('DRIFT', CSS);
}

const total = [...files.keys()].reduce((a, n) => a + (existsSync(DIR + n) ? statSync(DIR + n).size : 0), 0);
console.log(`${files.size} files, ${(total / 1024).toFixed(1)} KB -> ${DIR}`);

if (check) {
  console.log(drift ? `${drift} item(s) differ` : 'fonts match Google');
  process.exit(drift ? 1 : 0);
}
console.log(drift ? `wrote ${drift} item(s)` : 'already current');
